(library
 (name compiler)
 (libraries core sloth_common)
 ; https://dune.readthedocs.io/en/latest/quick-start.html#building-a-hello-world-program-using-core-and-jane-street-ppxs
 (preprocess
  (pps ppx_jane)))

(menhir
 (modules parser)
 ; https://gallium.inria.fr/~fpottier/menhir/manual.html#sec63
 (flags
  ; exn-carries-state -> Parser.Error of int
  --exn-carries-state
  ; COMMENTs are stripped out by the lexer footer post-processor
  --unused-token
  COMMENT
  --explain))

(ocamllex lexer)
