(library
 (name compiler)
 (libraries core sloth_common)
 ; https://dune.readthedocs.io/en/latest/quick-start.html#building-a-hello-world-program-using-core-and-jane-street-ppxs
 (preprocess
  (pps ppx_jane)))

(menhir
 (modules parser)
 ; https://gallium.inria.fr/~fpottier/menhir/manual.html#sec63
 (flags
  ; exn-carries-state -> Parser.Error of int
  --exn-carries-state
  ; COMMENTs are stripped out by the lexer footer post-processor
  --unused-token
  COMMENT
  --explain))

(ocamllex lexer)

; Auto-generate messages file

(rule
 (with-stdout-to
  parser.messages.auto
  (run menhir --unused-token COMMENT %{dep:parser.mly} --list-errors)))

;; Validate we've covered all possible messages
;
;(rule
; (with-stdout-to
;  messages.check
;  (run
;   menhir
;   --unused-token
;   COMMENT
;   %{dep:parser.mly}
;   --compare-errors
;   %{dep:.messages}
;   --compare-errors
;   %{dep:parser.messages})))

(rule
 (action
  (with-stdout-to
   parser-merged.messages
   (run
    menhir
    --unused-token
    COMMENT
    %{dep:parser.mly}
    --merge-errors
    %{dep:parser.messages.auto}
    --merge-errors
    %{dep:parser.messages})))
 (mode
  (promote (until-clean))))

(rule
 ;(deps messages.check)
 (action
  (with-stdout-to
   parser_errors.ml
   (run
    menhir
    --unused-token
    COMMENT
    %{dep:parser.mly}
    --compile-errors
    %{dep:parser-merged.messages}))))
