(data_only_dirs *_specs)

(test
 (name main)
 (libraries ounit2 sloth_script re core_unix unit_tests)
 (deps
  (source_tree green_specs)
  (source_tree red_specs))
 (modes byte))

(executable
 (public_name test_one)
 (name test_one)
 (libraries sloth_script re core_unix))

(executable
 (public_name train_runner)
 (name train)
 (libraries sloth_script core_unix re))

(rule
 (alias train)
 (deps
  (:specs
   ; TODO: once generating AST precludes running optimizer checks
   ; (source_tree red_specs)
   (source_tree green_specs))
  (file train.exe)
  ; Required to define a rule without any targets
  (universe))
 (action
  (run ./train.exe %{specs})))
