on: pull_request

jobs:
  # Set the job key. The key is displayed as the job name when a job name is
  # not provided
  all:
    # Name the job
    name: Run full CI suite
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    # This is the VM image
    runs-on: ubuntu-latest
    container:
      # As of May 2025, this is testing (bookworm is stable)
      image: debian:trixie-20250428-slim

    steps:
      # Check out repo
      - name: Check out repo
        uses: actions/checkout@v4.2.2
        with:
          #submodules: true
          # https://stackoverflow.com/questions/72978485/git-submodule-update-failed-with-fatal-detected-dubious-ownership-in-repositor
          set-safe-directory: true

      - name: Run CI
        shell: bash -exo pipefail {0}
        working-directory: ./tool
        run: make
