on:
  - push

jobs:
  # Set the job key. The key is displayed as the job name when a job name is
  # not provided
  all:
    # Name the job
    name: Run full CI suite
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    # This is the VM image
    runs-on: ubuntu-latest
    container:
      # As of May 2025, debian 12 is stable
      # As of May 2025, OCaml 5.3 is stable
      image: ocaml/opam:debian-12-ocaml-5.3

    steps:
      - name: Install OS deps
        shell: bash -exo pipefail {0}
        run: |
          sudo apt-get update
          sudo apt-get --yes upgrade
          sudo apt-get install --yes golang libreadline-dev

      - name: Chmod dirs
        shell: bash -exuo pipefail {0}
        run: |
          sudo chown "$(id -u):$(id -g)" "$GITHUB_WORKSPACE"
          sudo chmod -R 777 "$GITHUB_WORKSPACE"
          sudo chmod -R 777 "$RUNNER_TEMP"

      - name: Download doc-builder
        shell: bash -exuo pipefail {0}
        run: |
          #REF='da72ac8ccda2b1f088d86ca7dcbcfe70ea81a67c'
          #git clone https://github.com/christopherfujino/doc-builder ./db
          #cd db
          #git fetch
          #git checkout "$REF"
          #go get .
          #go build -o db .

          VERSION='0.5'
          ARCH='amd64'
          REMOTE="https://github.com/christopherfujino/doc-builder/releases/download/v${VERSION}/db-${VERSION}-linux-${ARCH}.tar.gz"
          curl -L "$REMOTE" -o db.tar.gz
          tar xvzf db.tar.gz
          mv "./db-${VERSION}-linux-${ARCH}" ./db

      - name: Check out repo
        shell: bash -exuo pipefail {0}
        run: |
          env
          REF=$(echo "${GITHUB_REF}" | sed -n 's/refs\/heads\/\(.*\)/\1/p')
          git clone "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" -b "${REF}"

      - name: Setup switch
        shell: bash -exuo pipefail {0}
        run: |
          opam init --bare --disable-sandboxing
          opam switch create default-switch 5.2.0
          opam install --yes dune ocamlformat

      - name: Run CI
        shell: bash -exuo pipefail {0}
        working-directory: ./slothscript
        run: |
          eval $(opam env --switch=default-switch)
          PATH="../db:$PATH"
          make docs
          make yolos
          make get
          make build
          PATH="./_build/default/bin:$PATH"
          make check-format
          make test
          make integration-tests
      # TODO use tool/ci.exe
      #  run: |
      #    eval $(opam env --switch=default-switch)
      #    dune exec tool/ci.exe
