on: pull_request

jobs:
  # Set the job key. The key is displayed as the job name when a job name is
  # not provided
  all:
    # Name the job
    name: Run full CI suite
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    # This is the VM image
    runs-on: ubuntu-latest
    container:
      # As of May 2025, debian 12 is stable
      # As of May 2025, OCaml 5.3 is stable
      image: ocaml/opam:debian-12-ocaml-5.3

    steps:
      #- name: Install OS deps
      #  shell: bash -exo pipefail {0}
      #  run: |
      #    apt-get update
      #    apt-get --yes upgrade
      #    apt-get install --yes make opam git

      #- name: Setup OCaml Deps
      #  shell: bash -exo pipefail {0}
      #  run: |
      #    opam init --bare --disable-sandboxing
      #    opam switch create default-switch 5.2.0
      #    echo 'eval $(opam env --switch=default-switch)' >> /root/.profile
      #    opam install --yes dune ocamlformat
      - name: Print debugging
        shell: bash -exuo pipefail {0}
        run: |
          env
          whoami
          echo "user:  $(id -u)"
          echo "group: $(id -g)"
          echo "PWD:   $PWD"
          sudo chown "$(id -u):$(id -g)" "$GITHUB_WORKSPACE"
          sudo chmod -R 777 "$GITHUB_WORKSPACE"
          sudo chmod -R 777 "$RUNNER_TEMP"
          ls -alh ..
          ls -alh .

      - name: Check out repo
        shell: bash -exuo pipefail {0}
        run: |
          git clone "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" -b "${GITHUB_HEAD_REF}" "${RUNNER_WORKSPACE}"
      ## Check out repo
      #- name: Check out repo
      #  uses: actions/checkout@v4.2.2
      #  with:
      #    #submodules: true
      #    # https://stackoverflow.com/questions/72978485/git-submodule-update-failed-with-fatal-detected-dubious-ownership-in-repositor
      #    set-safe-directory: true

      # TODO use //tool/ci.ml
      - name: Run CI
        shell: bash -exuo pipefail {0}
        run: |
          eval $(opam env --switch=default-switch)
          make get
          make build
          make test
